//Khai bao 1 file hang so
export const INCREMENT = 'INCREMENT Test'; 

export const DECREMENT = 'DECREMENT Test';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'; 

export const DELETE_USER_SUCCESS = 'DELETE_USER_ERROR'; 